use_frameworks!

platform :ios, '8.0'

target 'CocoapodKBDemo_Example' do
  pod 'CocoapodKBDemo', :path => '../'

  target 'CocoapodKBDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
